/**
 * This application allows to create extra routes manually by extending this array.
 * This approach is useful for pages generated by factories or a similar programmatic
 * approach.
 */
module.exports = [
  {
    name: 'test',
    path: '/test/',
    component: 'AreaEdit',
  },
]
